apiVersion: external-secrets.io/v1alpha1
kind: ClusterSecretStore
metadata:
  name: cluster-secret-store
spec:
  provider:
    yandexlockbox:
      auth:
        authorizedKeySecretRef:
          name: {{ .Values.clusterSecretStore.authSecret.name }}
          key: {{ .Values.clusterSecretStore.authSecret.key }}
