postgresName:
postgresZones:
  - "ru-central1-b"
postgresVersion: "14"
infraNamespace: "infrastructure"
securityGroupNames: []

dbUser:
dbPassword:
dbName:

diskSize: 10
resourcePresetId: "b1.medium"
diskTypeId: "network-hdd"
