# clusterName:
# clusterVersion: "1.27"
# clusterZone: "ru-central1-b"
# clusterIpv4Range:
# serviceIpv4Range:
# nodeCount: 1
# nodeDiskSize: 64
# nodeMem: 2
# nodeCores: 2
# securityGroup:
# nodeSubnet:
clusterName:
clusterVersion: "1.27"
masterType: zonal # Оставим по-умолчанию zonal
clusterZone: "ru-central1-b"
clusterIpv4Range:
serviceIpv4Range:
nodeCount: 1
nodeDiskSize: 64
nodeMem: 2
nodeCores: 2
securityGroup:
nodeSubnet:
releaseChannel: RAPID

autoscaling:
  enabled: false
  initialSize: 1
  minSize: 1
  maxSize: 5