apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: yc-alb-ingress-dev
  # Обратите внимание на namespace – он должен быть argocd
  namespace: argocd
spec:
  destination:
    # А вот тут уже неймспейс, куда будет устанавливаться сам чарт
    namespace: yc-alb-ingress
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    # Указываем путь до чарта
    path: charts/yc-alb-ingress-controller-chart
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
    helm:
      valueFiles:
        # указываем путь до values для дев кластера
        - secrets+age-import:///helm-secrets-private-keys/key.txt?../../values/alb-dev.yaml
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
