apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplane-dev
  # Обратите внимание на namespace – он должен быть argocd
  namespace: argocd
spec:
  destination:
    # А вот тут namespace, куда будет устанавливаться сам чарт
    namespace: crossplane-dev
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    # Указываем путь до чарта
    path: charts/crossplane
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
    helm:
      valueFiles:
        - secrets+age-import:///helm-secrets-private-keys/key.txt?../../values/crossplane-dev.yaml
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
  ignoreDifferences:
    - kind: ClusterRole
      group: rbac.authorization.k8s.io
      name: crossplane
      jsonPointers:
        - /rules
