apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: todobackend-test
  # Обратите внимание на namespace – он должен быть argocd
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: backend=cr.yandex/<id registry>/yc-courses/todobackend
    argocd-image-updater.argoproj.io/backend.update-strategy: latest
    # Добавляем regexp для деплоя только из ветки dev в test окружение
    argocd-image-updater.argoproj.io/backend.allow-tags: regexp:^dev-.*
spec:
  destination:
    # А вот тут уже неймспейс, куда будет устанавливаться сам чарт
    namespace: todobackend-test
    server: {{ .Values.spec.destination.server }}
  project: todoapp
  source:
    # Указываем путь до чарта
    path: charts/todobackend
    repoURL: {{ .Values.spec.source.appsRepoURL }}
    targetRevision: {{ .Values.spec.source.appsTargetRevision }}
    helm:
      valueFiles:
        # Не забываем прописать новый values файл для тестового контура
        - secrets+age-import:///helm-secrets-private-keys-apps/key.txt?../../values/todobackend-test.yaml
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true