apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: todofrontend-test
  # Обратите внимание на namespace – он должен быть argocd
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: front=cr.yandex/crpmb3eb0s24s0nc0nhh/kube/frontend
    argocd-image-updater.argoproj.io/front.update-strategy: latest
    # Добавляем еще одну аннотацию
    # Следим за образами собранными только из ветки dev
    argocd-image-updater.argoproj.io/front.allow-tags: regexp:^dev-.*
spec:
  destination:
    # А вот тут уже неймспейс, куда будет устанавливаться сам чарт
    namespace: todofrontend-test
    server: {{ .Values.spec.destination.server }}
  # Указываем новый проект todoapp
  project: todoapp
  source:
    # Указываем путь до чарта
    path: charts/todofrontend
    repoURL: {{ .Values.spec.source.appsRepoURL }}
    targetRevision: {{ .Values.spec.source.appsTargetRevision }}
    helm:
      valueFiles: 
        # указываем путь до values в репозитории todoapp
        - secrets+age-import:///helm-secrets-private-keys-apps/key.txt?../../values/todofrontend-test.yaml
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
