# apiVersion: mdb.yandex-cloud.jet.crossplane.io/v1alpha1
# kind: PostgresqlCluster
# metadata:
#   name: {{ include "postgresFullName" . }}
# spec:
#   forProvider:
#     # задаем имя кластера
#     name: {{ include "postgresFullName" . }}
#     # задаем каталог
#     folderIdRef:
#       name: default
#     # задаем сеть
#     networkIdRef:
#       name: default
#     # securityGroupIdsRefs:
#     #   - name: {{ .Values.securityGroup }}
#     {{- if .Values.securityGroupNames }}
#       securityGroupIdsRefs:
#       {{- range .Values.securityGroupNames }}
#         - name: {{ . }}
#       {{- end }}
#     {{- end }} 
#     config:
#       - resources:
#             # указываем размер диска
#           - diskSize: {{ .Values.diskSize }}
#             # указываем тип инстанса, их можно посмотреть с помощью команды
#             # yc postgres resource-preset list
#             resourcePresetId: {{ .Values.resourcePresetId }}
#             # задаем тип диска
#             diskTypeId: {{ .Values.diskTypeId }}
#         # указываем версию Posgtres
#         version: "{{ .Values.postgresVersion }}"
#     {{ if .Values.dbName }}
#     database:
#       - name: {{ .Values.dbName }}
#         owner: {{ .Values.dbUser }}
#     {{ end }}
#     # Указываем окружение
#     environment: PRODUCTION
#     host:
#       # задаем зону, в которой будет расположен кластер
#       - zone: {{ .Values.postgresZone }}
#     {{ if .Values.dbUser }}
#     user:
#       # создаем пользователя
#       - name: {{ .Values.dbUser }}
#         # указываем секрет, из которого брать пароль для создания пользователя
#         passwordSecretRef:
#           key: password
#           name: {{ include "postgresFullName" . }}-creds
#           namespace: {{ .Values.infraNamespace }}
#     {{ end }}
apiVersion: mdb.yandex-cloud.jet.crossplane.io/v1alpha1
kind: PostgresqlCluster
metadata:
  name: {{ include "postgresFullName" . }}
spec:
  forProvider:
    name: {{ include "postgresFullName" . }}
    folderIdRef:
      name: default
    networkIdRef:
      name: default
    {{- if .Values.securityGroupNames }}
    securityGroupIdsRefs:
    {{- range .Values.securityGroupNames }}
      - name: {{ . }}
    {{- end }}
    {{- end }}
    config:
      - resources:
          - diskSize: {{ .Values.diskSize }}
            resourcePresetId: {{ .Values.resourcePresetId }}
            diskTypeId: {{ .Values.diskTypeId }}
        version: "{{ .Values.postgresVersion }}"
    {{ if .Values.dbName }}
    database:
      - name: {{ .Values.dbName }}
        owner: {{ .Values.dbUser }}
    {{ end }}
    environment: PRODUCTION
    host:
    {{ range .Values.postgresZones }}
      - zone: {{ . }}
        subnetIdRef:
            name: default-{{ . }}
    {{ end }}
    {{ if .Values.dbUser }}
    user:
      - name: {{ .Values.dbUser }}
        passwordSecretRef:
          key: password
          name: {{ include "postgresFullName" . }}-creds
          namespace: {{ .Values.infraNamespace }}
    {{ end }}