# Добавляем условие на пользователя, чтобы не создавать секрет
{{ if .Values.dbUser }}
kind: Secret
apiVersion: v1
metadata:
  name: {{ include "postgresFullName" . }}-creds
  namespace: {{ .Values.infraNamespace }}
stringData:
  password: {{ .Values.dbPassword | quote }}
{{ end }}
