{{- if db.enabled }}
kind: Secret
apiVersion: v1
metadata:
  name: pass-{{ .Values.db.username | replace "_" "-" }}
  namespace: {{ .Release.Namespace }}
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-weight: "1"
data:
  password: {{ .Values.db.password | b64enc | quote }}
{{- end }}
