# {{- if .Values.dataTransfer.enabled }}
# apiVersion: datatransfer.yandex-cloud.jet.crossplane.io/v1alpha1
# kind: Endpoint
# metadata:
#   name: {{ include "todobackend.fullname" . }}-datatransfer-target
#     annotations:
#     helm.sh/hook: pre-install
#     helm.sh/hook-weight: "5"
# spec:
#   forProvider:
#     name: {{ include "todobackend.fullname" . }}-datatransfer-target
#     folderId: {{ .Values.dataTransfer.folderId }}
#     settings:
#       - postgresTarget:
#         - database: {{ .Values.dataTranfser.target.dbName }}
#           password:
#             - rawSecretRef:
#                 name: {{ .Values.dataTranfser.target.secretName }}
#                 namespace: {{ .Values.dataTranfser.target.secretNamespace }}
#                 key: password
#           user: {{ .Values.dataTranfser.target.username }}
#           connection:
#           - mdbClusterId: {{ .Values.dataTranfser.target.clusterId }}
# {{- end }}
apiVersion: datatransfer.yandex-cloud.jet.crossplane.io/v1alpha1 
kind: Endpoint
metadata:
  name: dynamic-target
spec:
  forProvider:
    name: dynamic-target
    folderId: b1giktpatd88fk2a7bss
    settings:
      - postgresTarget:
        - database: test-db
          password:
            - rawSecretRef:
                name: pass-test-user
                namespace: default
                key: password
          user: test-user
          connection:
          - mdbClusterId: c9qic6kd6tevkeoeg1bb
