# {{- if .Values.dataTransfer.enabled }}
# apiVersion: datatransfer.yandex-cloud.jet.crossplane.io/v1alpha1
# kind: Transfer
# metadata:
#   name: {{ include "todobackend.fullname" . }}-datatransfer-transfer
#     annotations:
#     helm.sh/hook: pre-install
#     helm.sh/hook-weight: "5"
# spec:
#   forProvider:
#     name: {{ include "todobackend.fullname" . }}-datatransfer-transfer
#     sourceIdRef:
#       name: {{ include "todobackend.fullname" . }}-datatransfer-source
#     targetIdRef:
#       name: {{ include "todobackend.fullname" . }}-datatransfer-target
#     type: {{ .Values.dataTranfser.transferType }}
#     folderId: {{ .Values.dataTransfer.folderId }}
# {{- end }}
apiVersion: datatransfer.yandex-cloud.jet.crossplane.io/v1alpha1
kind: Transfer
metadata:
  name: transfer
spec:
  forProvider:
    name: transfer
    sourceIdRef:
      name: prod-source
    targetIdRef:
      name: dynamic-target
    type: "SNAPSHOT_ONLY"
    folderId: b1giktpatd88fk2a7bss
