apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kyverno-policies
  # Обратите внимание на namespace – он должен быть argocd
  namespace: argocd
spec:
  destination:
    # А вот тут уже namespace, куда будет устанавливаться сам чарт
    namespace: kyverno
    name: {{ .Values.spec.destination.name }}
  project: default
  source:
    chart: kyverno-policies
    repoURL: https://kyverno.github.io/kyverno/
    targetRevision: 2.6.0
    helm:
      parameters:
        - name: validationFailureAction
          value: audit
        - name: podSecurityStandard
          value: restricted
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
