apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kyverno-custom-policices-frontend
  # Обратите внимание на namespace – он должен быть argocd
  namespace: argocd
spec:
  destination:
    # А тут уже namespace, куда будет устанавливаться сам чарт
        # Так как политики мы хотим применить только к фронтенду, 
        # укажем соответствующий namespace
    namespace: todofrontend
    name: {{ .Values.spec.destination.name }}
  project: default
  source:
    # Указываем путь до чарта
    path: charts/kyverno-custom-policices
    repoURL: {{ .Values.spec.source.appsRepoURL }}
    targetRevision: {{ .Values.spec.source.appsTargetRevision }}
  syncPolicy:
    automated: {}
    syncOptions: []
