stages:
  - say-hello

say-hello-job:
  stage: say-hello
  script:
    - echo "Hello world!"
    
after_script:
  - which curl &> /dev/null || apk add curl || (apt update; apt -y install curl)
  - >
    curl -X POST -H "Content-Type: application/json" -d "{\"parse_mode\": \"markdown\",\"disable_web_page_preview\": \"True\",\"chat_id\": \"${CHAT_ID}\",\"text\": \"Pipeline: [${CI_PIPELINE_NAME}/${CI_PIPELINE_ID}](${CI_PIPELINE_URL}), Job: [${CI_JOB_NAME}](${CI_JOB_URL}) => *${CI_JOB_STATUS}*\"}" https://api.telegram.org/bot${TOKEN}/sendMessage
